{% set name = "pyscf-dispersion" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyscf/dispersion/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a4ec720a27ce269df459409fd89bb6e9e725889c16339a8cdec1739dc36f8da6
build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - cmake >=3.26
    - make
  host:
    - libblas
    - liblapack
    - python
    - pip
    - setuptools
    - pyscf >=2.6
  run:
    - python
    - pyscf >=2.6
test:
  imports:
    - pyscf.dispersion.dftd3
    - pyscf.dispersion.dftd4
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pyscf/dispersion
  summary: "A collection of DFTD3 and DFTD4 with PySCF support"
  description: |
    "OpenMP is disabled in both DFTD3 and DFTD4"

  license: "Apache-2.0"
  license_family: "Apache"
  license_file: "LICENSE"

extra:
  recipe-maintainers:
    - wxj6000
